language: node_js
node_js:
  - "7"
cache:
  yarn: true
dist: trusty
sudo: required
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - jdk_switcher use oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
